export const FORM_SAVE_1 = "FORM_SAVE_1";
export const FORM_SAVE_2 = 'FORM_SAVE_2';
export const FORM_SAVE_3 = 'FORM_SAVE_3';
export const SET_INDEX = 'SET_INDEX';
export const BUSINESS_CHECKED = 'BUSINESS_CHECKED';
export const SET_DEBIT_PERSONAL_CHECKED = 'SET_DEBIT_PERSONAL_CHECKED';
export const SET_DEBIT_BUSINESS_CHECKED = 'SET_DEBIT_BUSINESS_CHECKED';
export const SET_POPULATE_USERS_LIST = 'SET_POPULATE_USERS_LIST';
export const RESET = 'RESET';
export const UPDATE_BUSINESS_ADDRESS = 'UPDATE_BUSINESS_ADDRESS';
export const UPDATE_DEBIT_ADDRESS = 'UPDATE_DEBIT_ADDRESS'


